spring:
  jpa:
    database-platform: com.jumia.j2pay.configs.SQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:sqlite:sample.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  application:
    name: j2pay-backend